config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    get 'dashboard', to: 'dashboard#index', as: :dashboard

    resources :cars
    resources :bookings
    resources :manufacturers
    resources :car_groups
  end
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
  has_many :cars
end

app/controllers/admin/manufacturers_controller.rb
class Admin::ManufacturersController < Admin::BaseController
  def index
    @manufacturers = Manufacturer.all
  end

  def show
    @manufacturer = Manufacturer.find(params[:id])
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def edit
    @manufacturer = Manufacturer.find(params[:id])
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)

    if  @manufacturer.save
      redirect_to admin_manufacturer_path(@manufacturer), notice: 'Manufacturer was successfully created.'
    else
      render 'new'
    end
  end

  def update
    @manufacturer = Manufacturer.find(params[:id])

    if @manufacturer.update(manufacturer_params)
      redirect_to admin_manufacturer_path(@manufacturer), notice: 'Manufacturer was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @manufacturer = Manufacturer.find(params[:id])
    @manufacturer.destroy

    redirect_to admin_manufacturers_path, notice: 'Manufacturer was successfully deleted.'
  end

  private

  def manufacturer_params
    params.require(:manufacturer).permit(:name)
  end
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/views/admin/manufacturers/_form.html.erb
<%= form_for [:admin, @manufacturer], local: true do |form| %>

  <% if @manufacturer.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@manufacturer.errors.count, "error") %> prohibited
        this manufacturer from being saved:
      </h2>
      <ul>
        <% @manufacturer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/admin/manufacturers/edit.html.erb
<h1>Edit Manufacturer</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_manufacturer_path %>

app/views/admin/manufacturers/index.html.erb
<h2>Manufacturers</h2>

<table>
  <thead>
      <tr>
        <th>Name</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @manufacturers.each do |manufacturer| %>
        <tr>
          <td><%= manufacturer.name %></td>
          <td><%= link_to 'Show', admin_manufacturer_path(manufacturer) %></td>
          <td><%= link_to 'Edit', edit_admin_manufacturer_path(manufacturer) %></td>
          <td><%= link_to 'Delete', admin_manufacturer_path(manufacturer),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New manufacturer', new_admin_manufacturer_path %>

app/views/admin/manufacturers/new.html.erb
<h1>New Manufacturer</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_manufacturers_path %>

app/views/admin/manufacturers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @manufacturer.name %>
</p>

<%= link_to 'Back', admin_manufacturers_path %>