config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
    get 'dashboard', to: 'dashboard#index', as: :dashboard

    resources :cars
    resources :bookings
    resources :manufacturers
    resources :car_groups
  end
end

app/models/car_group.rb
class CarGroup < ApplicationRecord
  has_many :cars
end

app/controllers/admin/car_groups_controller.rb
class Admin::CarGroupsController < Admin::BaseController
  def index
    @car_groups = CarGroup.all
  end

  def show
    @car_group = CarGroup.find(params[:id])
  end

  def new
    @car_group = CarGroup.new
  end

  def edit
    @car_group = CarGroup.find(params[:id])
  end

  def create
    @car_group = CarGroup.new(car_group_params)

    if  @car_group.save
      redirect_to admin_car_group_path(@car_group), notice: 'Car Group was successfully created.'
    else
      render 'new'
    end
  end

  def update
    @car_group = CarGroup.find(params[:id])

    if @car_group.update(car_group_params)
      redirect_to admin_car_group_path(@car_group), notice: 'Car Group was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @car_group = CarGroup.find(params[:id])
    @car_group.destroy

    redirect_to admin_car_groups_path, notice: 'Car Group was successfully deleted.'
  end

  private

  def car_group_params
    params.require(:car_group).permit(:name)
  end
end

app/helpers/car_groups_helper.rb
module CarGroupsHelper
end

app/views/admin/car_groups/_form.html.erb
<%= form_for [:admin, @car_group], local: true do |form| %>

  <% if @car_group.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@car_group.errors.count, "error") %> prohibited
        this car group from being saved:
      </h2>
      <ul>
        <% @car_group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/admin/car_groups/edit.html.erb
<h1>Edit Car Group</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_car_groups_path %>

app/views/admin/car_groups/index.html.erb
<h2>Car Groups</h2>

<table>
  <thead>
      <tr>
        <th>Name</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @car_groups.each do |car_group| %>
        <tr>
          <td><%= car_group.name %></td>
          <td><%= link_to 'Show', admin_car_group_path(car_group) %></td>
          <td><%= link_to 'Edit', edit_admin_car_group_path(car_group) %></td>
          <td><%= link_to 'Delete', admin_car_group_path(car_group),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Car Group', new_admin_car_group_path %>

app/views/admin/car_groups/new.html.erb
<h1>New Car Group</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_car_groups_path %>

app/views/admin/car_groups/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @car_group.name %>
</p>

<%= link_to 'Back', admin_car_groups_path %>